[*]
version = 1

[Model A (non-thinking)]
model = ./models/Qwen2.5-0.5B-Instruct-Q4_K_M.gguf
load-on-startup = true

[Model B (thinking)]
model = ./models/Qwen3-0.6B-Q4_K_M.gguf
load-on-startup = true

; [Model C (OCR)]
; load-on-startup = true
